type GithubAuthor {
  nickname: String!
  url: String!
  slug: String
  name: String
  permalink: Permalink
}

type Permalink {
  fr: String
  en: String
}

type GithubJson implements Node @infer {
  repo: String!
  language: String
  url: String
  startDate: String
  endDate: String
  count: Int
  description: String
  license: String
  authors: [GithubAuthor!]
}

type OriginalTweet {
  tweet: String!
  text: String!
  html: String!
  screenName: String!
  name: String!
  type: String!
}

type TwitterJson implements Node @infer {
  tweet: String!
  text: String!
  html: String!
  date: String
  retweets: Int
  favorites: Int
  type: String!
  originalTweet: OriginalTweet
}
