apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api/pvc.yml
  - api/deployment.yml
  - api/service.yml
  - web/deployment.yml
  - web/service.yml

commonLabels:
  owner: medialab
  app: website
