apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      imagePullSecrets:
        - name: gitlab
      containers:
        - name: web
          image: gitlab.sciences-po.fr:4567/medialab/website/website_web:latest
          env:
            - name: API_HOST
              value: website-api.website.svc.cluster.local
            - name: API_PORT
              value: '3000'
          imagePullPolicy: Always
