apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: website

namePrefix: website-

bases:
  - ../../base/

resources:
  - ingress.yml

patchesStrategicMerge:
  - env.yml

commonLabels:
  stage: staging

images:
  - name: gitlab.sciences-po.fr:4567/medialab/website/website_api
    newTag: 'staging'
  - name: gitlab.sciences-po.fr:4567/medialab/website/website_web
    newTag: 'staging'
